In [19]:
import pandas as pd
import numpy as np

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
df = pd.read_csv('/content/canada_per_capita_income.csv')

In [22]:
df.head()

,year,per capita income (US$)
0,1970,3399.299037
1,1971,3768.297935
2,1972,4251.175484
3,1973,4804.463248
4,1974,5576.514583


In [23]:
df.isnull().sum()

,0
year,0
per capita income (US$),0


In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
model=LinearRegression()
model.fit(df[['year']],df['per capita income (US$)'])

LinearRegression()

In [26]:
accuracy_score = model.score(df[['year']],df['per capita income (US$)'])
print(accuracy_score)

0.890916917957032


In [27]:
model.predict([[1971]])

array([693.9054085])

In [28]:
model.score(df[['year']],df['per capita income (US$)'])

0.890916917957032

In [29]:
model.coef_

array([828.46507522])

In [30]:
model.intercept_

np.float64(-1632210.7578554575)

In [31]:
model.predict([[2020]])

array([41288.69409442])

In [32]:
model.predict([[2018]])

array([39631.76394397])